
package lameDuckClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "bookingFailedException", targetNamespace = "http://LameDuck.ws")
public class BookingFailedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookingFailedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookingFailedFault(String message, BookingFailedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookingFailedFault(String message, BookingFailedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: lameDuckClient.BookingFailedException
     */
    public BookingFailedException getFaultInfo() {
        return faultInfo;
    }

}
