<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="LameDuckWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/LameDuckWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/LameDuckWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://LameDuck.ws">
    <import location="file:/C:/Users/Troels/Dropbox/DTU/02267%20Software%20Development%20of%20Web%20Services/GITv2/SDoWS_TeamAwesome/LameDuck/src/java/lameduck/auxiliarytypes/LameDuck.wsdl" namespace="http://LameDuck.ws"/>
    <plnk:partnerLinkType name="LameDuckLinkType">
        <plnk:role name="LameDuckRole" portType="ns:LameDuck"/>
    </plnk:partnerLinkType>
</definitions>
