
package niceViewClient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "bookingFailedFault", targetNamespace = "http://niceview.ws")
public class BookingFailedMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BookingFailedFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BookingFailedMessage(String message, BookingFailedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BookingFailedMessage(String message, BookingFailedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: niceViewClient.BookingFailedFaultType
     */
    public BookingFailedFaultType getFaultInfo() {
        return faultInfo;
    }

}
