
package niceViewClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NiceView", targetNamespace = "http://niceview.ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NiceView {


    /**
     * 
     * @param request
     * @return
     *     returns niceViewClient.HotelList
     */
    @WebMethod
    @WebResult(name = "hotelList", targetNamespace = "http://niceview.ws", partName = "response")
    public HotelList getHotels(
        @WebParam(name = "getHotelsRequest", targetNamespace = "http://niceview.ws", partName = "request")
        GetHotelsRequest request);

    /**
     * 
     * @param parameters
     * @return
     *     returns boolean
     * @throws BookingFailedMessage
     */
    @WebMethod
    @WebResult(name = "success", targetNamespace = "http://niceview.ws", partName = "parameters")
    public boolean bookHotel(
        @WebParam(name = "bookHotelRequest", targetNamespace = "http://niceview.ws", partName = "parameters")
        BookHotelRequest parameters)
        throws BookingFailedMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns boolean
     * @throws CancellingFailedMessage
     */
    @WebMethod
    @WebResult(name = "success", targetNamespace = "http://niceview.ws", partName = "response")
    public boolean cancelHotel(
        @WebParam(name = "cancelHotelRequest", targetNamespace = "http://niceview.ws", partName = "parameters")
        CancelHotelRequest parameters)
        throws CancellingFailedMessage
    ;

}
